version: "3.7"
services:

  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
    volumes: ['./api:/api']

  worker:
    build:
      context: ./celeryQueue
      dockerfile: Dockerfile
    command: celery -A tasks worker -l debug -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./celeryQueue:/queue']

  beat:
    build:
      context: ./celeryQueue
      dockerfile: Dockerfile
    command: celery -A tasks beat -S redbeat.RedBeatScheduler -l debug --max-interval 5
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./celeryQueue:/queue']

  monitor:
    build:
      context: ./celeryQueue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    command: ['celery', '-A', 'tasks', 'flower']
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
    volumes: ['./celeryQueue:/queue']

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

    # command: celery -A run.celery beat -S redbeat.RedBeatScheduler --loglevel=info
