version: "3.7"
services:

  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
    volumes: ['./api:/api']

  trader:
    build:
      context: ./trader
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./trader:/queue']

  orderer:
    build:
      context: ./orderer
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -E -Q orders
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./orderer:/queue']

  beat:
    build:
      context: ./trader
      dockerfile: Dockerfile
    command: celery -A tasks beat -S redbeat.RedBeatScheduler -l info --max-interval 5
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./trader:/queue']

  monitor:
    build:
      context: ./trader
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    command: ['celery', '-A', 'tasks', 'flower']
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - trader
      - orderer
    volumes: ['./trader:/queue']

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
