version: "3.7"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./app.py
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
    volumes: ['./api:/api']
  worker:
    build:
      context: ./trader
      dockerfile: Dockerfile.dev
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./trader:/queue']
  monitor:
    build:
      context: ./trader
      dockerfile: Dockerfile.dev
    ports:
     - "5555:5555"
    command:  celery -A tasks beat -P gevent -S redbeat.RedBeatScheduler --max-interval 30 loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
    volumes: ['./trader:/queue']
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
